const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => Array.from(document.querySelectorAll(sel));

const state = {
  posts: [],
  applications: [],
  selectedApplicationId: null,
  schoolConnect: [],
  selectedRegistrationId: null,
  subscribers: [],
  content: [],
  newsletter: { content: null, campaigns: [], stats: {}, hasProvider: false },
  editingPostId: null,
};

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function slugify(text) {
  return String(text)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

async function api(path, { method = 'GET', body } = {}) {
  const res = await fetch(path, {
    method,
    credentials: 'same-origin',
    headers: body ? { 'Content-Type': 'application/json' } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(json.error || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  return json;
}

function flash(message, type = 'ok') {
  const el = $('#flash');
  el.textContent = message;
  el.className = 'flash' + (type === 'error' ? ' error' : '');
  clearTimeout(el._t);
  el._t = setTimeout(() => el.classList.add('hidden'), 3000);
}

function show(view) {
  $$('.tab').forEach((t) => t.classList.toggle('active', t.dataset.view === view));
  $$('.view').forEach((v) => v.classList.toggle('active', v.id === `view-${view}`));
}

function formatDate(value) {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

// ---------- Auth ----------
async function bootstrap() {
  try {
    const me = await api('/api/auth/me');
    $('#who').textContent = me.email;
    $('#login-view').classList.add('hidden');
    $('#app-view').classList.remove('hidden');
    await Promise.all([loadPosts(), loadApplications(), loadSubscribers(), loadContent(), loadNewsletter()]);
    await loadSchoolConnect();
  } catch {
    $('#app-view').classList.add('hidden');
    $('#login-view').classList.remove('hidden');
  }
}

$('#login-form').addEventListener('submit', async (e) => {
  e.preventDefault();
  const email = $('#login-email').value.trim();
  const password = $('#login-password').value;
  $('#login-error').textContent = '';
  try {
    await api('/api/auth/login', { method: 'POST', body: { email, password } });
    await bootstrap();
  } catch (err) {
    $('#login-error').textContent = err.message;
  }
});

$('#logout-btn').addEventListener('click', async () => {
  try { await api('/api/auth/logout', { method: 'POST' }); } catch {}
  $('#who').textContent = '';
  $('#app-view').classList.add('hidden');
  $('#login-view').classList.remove('hidden');
});

// ---------- Tabs ----------
$$('.tab').forEach((tab) =>
  tab.addEventListener('click', () => show(tab.dataset.view))
);

// ---------- Posts ----------
async function loadPosts() {
  const { posts } = await api('/api/admin/posts');
  state.posts = posts;
  $('#count-posts').textContent = posts.length;
  renderPosts();
}

function renderPosts() {
  const list = $('#posts-list');
  if (!state.posts.length) {
    list.innerHTML = '<div class="empty">No posts yet. Create your first post.</div>';
    return;
  }
  list.innerHTML = state.posts
    .map((p) => {
      const statusBadge = p.published ? 'published' : 'draft';
      const aiBadge = p.source === 'ai'
        ? '<span class="badge ai" title="Generated by AI">AI</span> '
        : '';
      const publishBtn = p.published
        ? '<button class="btn btn-sm btn-ghost" data-unpublish="' + p.id + '">Unpublish</button>'
        : '<button class="btn btn-sm btn-success" data-publish="' + p.id + '">' + (p.source === 'ai' ? 'Approve & Publish' : 'Publish') + '</button>';
      return `
        <div class="card">
          <div class="meta">
            <div class="title">${aiBadge}${escapeHtml(p.title)}</div>
            <div class="sub">${escapeHtml(p.category || 'Uncategorized')} · Updated ${formatDate(p.updated_at)}</div>
          </div>
          <div style="display:flex;align-items:center;gap:12px;">
            <span class="badge ${statusBadge}">${p.published ? 'Published' : 'Draft'}</span>
            <div class="row-actions">
              <button class="btn btn-sm btn-ghost" data-edit="${p.id}">Edit</button>
              ${publishBtn}
              <button class="btn btn-sm btn-danger" data-delete="${p.id}">Delete</button>
            </div>
          </div>
        </div>`;
    })
    .join('');

  $$('[data-edit]').forEach((btn) =>
    btn.addEventListener('click', () => openPostEditor(Number(btn.dataset.edit)))
  );
  $$('[data-publish]').forEach((btn) =>
    btn.addEventListener('click', () => setPublished(Number(btn.dataset.publish), true))
  );
  $$('[data-unpublish]').forEach((btn) =>
    btn.addEventListener('click', () => setPublished(Number(btn.dataset.unpublish), false))
  );
  $$('[data-delete]').forEach((btn) =>
    btn.addEventListener('click', () => deletePost(Number(btn.dataset.delete)))
  );
}

$('#new-post-btn').addEventListener('click', () => openPostEditor(null));

$('#generate-post-btn').addEventListener('click', async () => {
  const btn = $('#generate-post-btn');
  btn.disabled = true;
  btn.textContent = 'Generating…';
  try {
    const { post } = await api('/api/admin/generate', { method: 'POST', body: {} });
    flash(`Draft created: ${post.title}`);
    await loadPosts();
    openPostEditor(post.id);
  } catch (err) {
    flash(err.message, 'error');
  } finally {
    btn.disabled = false;
    btn.textContent = '✨ AI Generate';
  }
});

async function setPublished(id, published) {
  try {
    // Fetch the full post, then re-save with the new published state.
    const { post: full } = await api(`/api/admin/posts/${id}`);
    await api(`/api/admin/posts/${id}`, {
      method: 'PUT',
      body: {
        title: full.title,
        slug: full.slug,
        category: full.category,
        cover_image: full.cover_image,
        author: full.author,
        excerpt: full.excerpt,
        body: full.body,
        published,
      },
    });
    flash(published ? 'Post published' : 'Post moved to draft');
    await loadPosts();
  } catch (err) {
    flash(err.message, 'error');
  }
}

function openPostEditor(id) {
  state.editingPostId = id;
  const post = id ? state.posts.find((p) => p.id === id) : null;
  $('#post-modal-title').textContent = post ? 'Edit Post' : 'New Post';
  $('#p-title').value = post?.title || '';
  $('#p-slug').value = post?.slug || '';
  $('#p-category').value = post?.category || '';
  $('#p-cover').value = post?.cover_image || '';
  $('#p-author').value = post?.author || 'Hash Future School';
  $('#p-excerpt').value = post?.excerpt || '';
  $('#p-body').value = '';
  $('#p-published').checked = post?.published || false;
  $('#post-modal').classList.remove('hidden');

  if (id) {
    api(`/api/admin/posts/${id}`).then(({ post: full }) => {
      if (state.editingPostId === id) $('#p-body').value = full.body || '';
    }).catch(() => {});
  }
}

function closePostEditor() {
  $('#post-modal').classList.add('hidden');
}

$('#post-modal-close').addEventListener('click', closePostEditor);
$('#post-modal-cancel').addEventListener('click', closePostEditor);

$('#p-title').addEventListener('input', () => {
  const slugInput = $('#p-slug');
  if (!slugInput.dataset.manual) slugInput.value = slugify($('#p-title').value);
});
$('#p-slug').addEventListener('input', () => { $('#p-slug').dataset.manual = '1'; });

$('#post-modal-save').addEventListener('click', async () => {
  const body = {
    title: $('#p-title').value,
    slug: $('#p-slug').value,
    category: $('#p-category').value,
    cover_image: $('#p-cover').value,
    author: $('#p-author').value,
    excerpt: $('#p-excerpt').value,
    body: $('#p-body').value,
    published: $('#p-published').checked,
  };
  try {
    if (state.editingPostId) {
      await api(`/api/admin/posts/${state.editingPostId}`, { method: 'PUT', body });
      flash('Post updated');
    } else {
      await api('/api/admin/posts', { method: 'POST', body });
      flash('Post created');
    }
    closePostEditor();
    await loadPosts();
  } catch (err) {
    flash(err.message, 'error');
  }
});

async function deletePost(id) {
  if (!confirm('Delete this post? This cannot be undone.')) return;
  try {
    await api(`/api/admin/posts/${id}`, { method: 'DELETE' });
    flash('Post deleted');
    await loadPosts();
  } catch (err) {
    flash(err.message, 'error');
  }
}

// ---------- Subscribers ----------
async function loadSubscribers() {
  const { subscribers } = await api('/api/admin/subscribers');
  state.subscribers = subscribers;
  $('#count-subs').textContent = subscribers.filter((s) => s.status === 'active').length;
  renderSubscribers();
}

function renderSubscribers() {
  const list = $('#subs-list');
  if (!state.subscribers.length) {
    list.innerHTML = '<div class="empty">No subscribers yet.</div>';
    return;
  }
  list.innerHTML = state.subscribers
    .map((s) => {
      const badge = s.status === 'active' ? 'active' : 'unsubscribed';
      return `
        <div class="card">
          <div class="meta">
            <div class="title">${escapeHtml(s.email)}</div>
            <div class="sub">${escapeHtml(s.name || 'No name')} · Joined ${formatDate(s.subscribed_at)}</div>
          </div>
          <div style="display:flex;align-items:center;gap:12px;">
            <span class="badge ${badge}">${s.status}</span>
            <div class="row-actions">
              <button class="btn btn-sm btn-success" data-toggle="${s.id}" data-status="${s.status === 'active' ? 'unsubscribed' : 'active'}">
                ${s.status === 'active' ? 'Unsubscribe' : 'Activate'}
              </button>
              <button class="btn btn-sm btn-danger" data-remove="${s.id}">Delete</button>
            </div>
          </div>
        </div>`;
    })
    .join('');

  $$('[data-toggle]').forEach((btn) =>
    btn.addEventListener('click', () => setSubscriberStatus(Number(btn.dataset.toggle), btn.dataset.status))
  );
  $$('[data-remove]').forEach((btn) =>
    btn.addEventListener('click', () => deleteSubscriber(Number(btn.dataset.remove)))
  );
}

async function setSubscriberStatus(id, status) {
  try {
    await api(`/api/admin/subscribers/${id}`, { method: 'PATCH', body: { status } });
    flash('Subscriber updated');
    await loadSubscribers();
  } catch (err) {
    flash(err.message, 'error');
  }
}

async function deleteSubscriber(id) {
  if (!confirm('Delete this subscriber?')) return;
  try {
    await api(`/api/admin/subscribers/${id}`, { method: 'DELETE' });
    flash('Subscriber removed');
    await loadSubscribers();
  } catch (err) {
    flash(err.message, 'error');
  }
}

// ---------- Newsletter ----------
async function loadNewsletter() {
  try {
    state.newsletter = await api('/api/admin/newsletter');
    renderNewsletter();
  } catch (err) {
    flash(err.message, 'error');
  }
}

function renderNewsletter() {
  const { content, campaigns, stats } = state.newsletter;
  const subjectEl = $('#nl-subject');
  const bodyEl = $('#nl-body');
  const countEl = $('#nl-active-count');
  const statusEl = $('#nl-status');

  if (subjectEl) subjectEl.value = content?.subject || '';
  if (bodyEl) bodyEl.value = content?.bodyMd || '';
  if (countEl) countEl.value = String(stats?.activeSubscribers ?? 0);
  if (statusEl) {
    statusEl.textContent = state.newsletter.hasProvider
      ? '✅ Provider ready'
      : '⚠️ MAILGUN_API_KEY not set';
    statusEl.className = 'pill ' + (state.newsletter.hasProvider ? 'ok' : 'warn');
  }

  const list = $('#nl-campaigns');
  if (!list) return;
  if (!campaigns || !campaigns.length) {
    list.innerHTML = '<div class="empty">No sends yet. Click “Send Now” to deliver your first weekly newsletter.</div>';
    return;
  }

  list.innerHTML = campaigns
    .map((c) => {
      const badgeClass =
        c.status === 'sent' ? 'published'
        : c.status === 'failed' ? 'unsubscribed'
        : c.status === 'partial' ? 'draft'
        : 'unsubscribed';
      return `
        <div class="card">
          <div class="meta">
            <div class="title">${escapeHtml(c.subject)}</div>
            <div class="sub">${formatDate(c.createdAt)} · ${escapeHtml(c.trigger)}</div>
          </div>
          <div style="display:flex;align-items:center;gap:12px;">
            <span class="badge ${badgeClass}">${escapeHtml(c.status)}</span>
            <div class="sub" style="margin-left:auto;">${c.recipientCount} to · ${c.sentCount} sent · ${c.failedCount} failed</div>
          </div>
        </div>`;
    })
    .join('');
}

$('#save-newsletter-btn').addEventListener('click', async () => {
  try {
    const data = await api('/api/admin/newsletter', {
      method: 'PUT',
      body: { subject: $('#nl-subject').value, body: $('#nl-body').value },
    });
    state.newsletter.content = data.content;
    flash('Newsletter content saved');
  } catch (err) {
    flash(err.message, 'error');
  }
});

$('#send-newsletter-btn').addEventListener('click', async () => {
  if (!confirm('Send this newsletter to all active subscribers now?')) return;
  const btn = $('#send-newsletter-btn');
  btn.disabled = true;
  const old = btn.textContent;
  btn.textContent = 'Sending…';
  try {
    const data = await api('/api/admin/newsletter/send', { method: 'POST' });
    flash(`Newsletter sent to ${data.campaign.scheduled} subscriber(s): ${data.campaign.sent} delivered, ${data.campaign.failed} failed.`);
    await loadNewsletter();
  } catch (err) {
    flash(err.message, 'error');
  } finally {
    btn.disabled = false;
    btn.textContent = old;
  }
});

// ---------- Team Applications ----------
const APP_STATUS_LABELS = {
  new: 'New',
  shortlisted: 'Shortlisted',
  'in-conversation': 'In conversation',
  invited: 'Invited',
  hired: 'Hired',
  archived: 'Archived',
};

function appStatusBadge(status) {
  const known = ['new', 'shortlisted', 'in-conversation', 'invited', 'hired', 'archived'];
  const cls = known.includes(status) ? status : 'new';
  return `<span class="badge status-${cls}">${escapeHtml(APP_STATUS_LABELS[status] || status || 'New')}</span>`;
}

async function loadApplications() {
  const { applications } = await api('/api/admin/applications');
  state.applications = applications;
  $('#count-apps').textContent = applications.length;
  renderApplications();
}

function renderApplications() {
  const list = $('#apps-list');
  const filter = $('#apps-filter').value;
  const rows = filter ? state.applications.filter((a) => a.status === filter) : state.applications;

  if (!rows.length) {
    list.innerHTML = state.applications.length
      ? '<div class="empty">No applications with this status.</div>'
      : '<div class="empty">No applications yet. They arrive here the moment someone applies at /join.</div>';
    return;
  }

  list.innerHTML = rows
    .map((a) => {
      const skills = Array.isArray(a.skills) ? a.skills.slice(0, 4) : [];
      return `
        <div class="card app-card">
          <div class="meta" style="flex:1;">
            <div class="title">${escapeHtml(a.full_name)} ${appStatusBadge(a.status)}</div>
            <div class="sub">
              ${escapeHtml(a.ref || '—')} · ${escapeHtml(a.email)} · ${escapeHtml(a.location || 'Location not given')}
              ${a.role_interest ? ` · ${escapeHtml(a.role_interest)}` : ''}
            </div>
            <div class="sub" style="margin-top:6px;">
              ${a.achievement_count || 0} achievement${a.achievement_count === 1 ? '' : 's'}
              ${a.commitment ? ` · ${escapeHtml(a.commitment)}` : ''}
              ${a.future_assist_state && a.future_assist_state !== 'synced'
                ? ` · <span style="color:#b45309;">Future Assist: ${escapeHtml(a.future_assist_state)}</span>`
                : ''}
            </div>
            ${skills.length ? `<div class="chip-row">${skills.map((s) => `<span class="chip">${escapeHtml(s)}</span>`).join('')}</div>` : ''}
          </div>
          <div class="sub" style="white-space:nowrap;color:var(--muted);font-size:0.82rem;">${formatDate(a.created_at)}</div>
          <div class="row-actions">
            <button class="btn btn-ghost btn-sm" data-app-open="${a.id}" type="button">Read →</button>
          </div>
        </div>`;
    })
    .join('');

  $$('#apps-list [data-app-open]').forEach((btn) =>
    btn.addEventListener('click', () => openApplication(Number(btn.dataset.appOpen)))
  );
}

async function openApplication(id) {
  const { application } = await api(`/api/admin/applications/${id}`);
  state.selectedApplicationId = id;

  const achievements = Array.isArray(application.achievements) ? application.achievements : [];
  const skills = Array.isArray(application.skills) ? application.skills : [];

  const block = (label, value) =>
    value
      ? `<div class="app-block"><div class="app-label">${escapeHtml(label)}</div><div class="app-value">${escapeHtml(value)}</div></div>`
      : '';

  // Applicants can list several links, stored one per line.
  const linksBlock = (value) => {
    const list = String(value || '')
      .split(/[\n,]+/)
      .map((l) => l.trim())
      .filter(Boolean);
    if (!list.length) return '';
    const anchors = list
      .map((l) => {
        const href = /^https?:\/\//i.test(l) ? l : `https://${l}`;
        return `<a href="${escapeHtml(href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(l)}</a>`;
      })
      .join('<br>');
    return `<div class="app-block"><div class="app-label">Links</div><div class="app-value">${anchors}</div></div>`;
  };

  const videoBlock = (app) => {
    const value = app.video_url;
    if (!value) return '';
    const href = /^https?:\/\//i.test(value) ? value : `https://${value}`;
    const confirmed = app.video_language_confirmed
      ? '<span class="video-flag ok">Confirmed: spoken in English</span>'
      : '<span class="video-flag warn">English not confirmed</span>';
    return `<div class="video-block">
      <div class="app-label">🎥 Intro video (3–5 min)</div>
      <a href="${escapeHtml(href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(value)}</a>
      ${confirmed}
      <span class="video-note">Watch before the conversation.</span>
    </div>`;
  };

  $('#app-modal-title').innerHTML = `${escapeHtml(application.full_name)} <span class="pill">${escapeHtml(application.ref || '')}</span>`;
  $('#app-modal-body').innerHTML = `
    <div class="app-grid">
      ${block('Email', application.email)}
      ${block('Phone / WhatsApp', application.phone)}
      ${block('City, Country', application.location)}
      ${block('Age', application.age)}
      ${block('Education (optional)', application.education)}
      ${linksBlock(application.links)}
    </div>

    <h4 class="app-section">What they have actually done</h4>
    ${videoBlock(application)}
    ${
      achievements.length
        ? achievements
            .map(
              (x) => `
      <div class="achievement">
        <div class="achievement-head">${escapeHtml(x.title || 'Untitled')}${
          x.when ? ` <span class="sub">· ${escapeHtml(x.when)}</span>` : ''
        }</div>
        ${x.what ? `<div class="app-value">${escapeHtml(x.what)}</div>` : ''}
        ${x.link ? `<div class="sub"><a href="${escapeHtml(x.link)}" target="_blank" rel="noopener">${escapeHtml(x.link)}</a></div>` : ''}
      </div>`
            )
            .join('')
        : '<div class="empty" style="padding:12px 0;">No achievements listed.</div>'
    }
    ${skills.length ? `<div class="chip-row">${skills.map((s) => `<span class="chip">${escapeHtml(s)}</span>`).join('')}</div>` : ''}
    ${block('Proof no certificate can show', application.proof_of_work)}

    <h4 class="app-section">What they want to change &amp; contribute</h4>
    ${block('What they want to change in the world', application.world_change)}
    ${block('What they would contribute to this ecosystem', application.contribution)}
    ${block('Wants to work on', application.role_interest)}
    ${block('Commitment', application.commitment)}
    ${block('Available from', application.availability)}
    ${block('Heard about us via', application.hearsay)}
    ${block('Anything else', application.extra)}

    <div class="app-grid app-meta-grid">
      ${block('Applied', formatDate(application.created_at))}
      ${block('Future Assist', application.future_assist_state)}
      ${application.future_assist_error ? block('Sync error', application.future_assist_error) : ''}
    </div>`;

  $('#app-status').value = application.status || 'new';
  $('#app-score').value = application.score ?? '';
  $('#app-notes').value = application.reviewer_notes ?? '';

  $('#app-modal').classList.remove('hidden');
}

function closeApplicationModal() {
  $('#app-modal').classList.add('hidden');
  state.selectedApplicationId = null;
}

$('#app-modal-close').addEventListener('click', closeApplicationModal);
$('#app-modal-close-2').addEventListener('click', closeApplicationModal);

$('#app-modal').addEventListener('click', (e) => {
  if (e.target === $('#app-modal')) closeApplicationModal();
});

$('#app-save-btn').addEventListener('click', async () => {
  const id = state.selectedApplicationId;
  if (!id) return;
  const btn = $('#app-save-btn');
  btn.disabled = true;
  const old = btn.textContent;
  btn.textContent = 'Saving…';
  try {
    const body = {
      status: $('#app-status').value,
      reviewer_notes: $('#app-notes').value,
    };
    const score = $('#app-score').value;
    if (score !== '') body.score = Number(score);

    await api(`/api/admin/applications/${id}`, { method: 'PATCH', body });
    flash('Application updated');
    await loadApplications();
    closeApplicationModal();
  } catch (err) {
    flash(err.message, 'error');
  } finally {
    btn.disabled = false;
    btn.textContent = old;
  }
});

$('#apps-filter').addEventListener('change', renderApplications);
$('#apps-refresh-btn').addEventListener('click', async () => {
  try {
    await loadApplications();
    flash('Applications refreshed');
  } catch (err) {
    flash(err.message, 'error');
  }
});

// ---------- IIT Madras School Connect ----------

// Registrations from students who study at another school and want to take an
// IIT Madras School Connect course as a Hash Future School student.
const SC_STATUS_LABELS = {
  new: 'New',
  verified: 'Verified',
  approved: 'Approved',
  rejected: 'Rejected',
  archived: 'Archived',
};

function scStatusBadge(status) {
  const cls = SC_STATUS_LABELS[status] ? status : 'new';
  return `<span class="badge status-${cls === 'in-conversation' ? 'new' : cls}">${escapeHtml(
    SC_STATUS_LABELS[status] || status || 'New'
  )}</span>`;
}

async function loadSchoolConnect() {
  try {
    const { registrations, migrationRequired } = await api('/api/admin/school-connect');
    state.schoolConnect = registrations || [];
    $('#count-sc').textContent = state.schoolConnect.length;
    if (migrationRequired) {
      $('#sc-list').innerHTML =
        '<div class="empty">The <code>school_connect_registrations</code> table does not exist on this database yet. Run <code>npm run db:migrate</code>.</div>';
      return;
    }
    renderSchoolConnect();
  } catch (err) {
    $('#sc-list').innerHTML = `<div class="empty">${escapeHtml(err.message)}</div>`;
  }
}

function renderSchoolConnect() {
  const list = $('#sc-list');
  const filter = $('#sc-filter').value;
  const rows = filter ? state.schoolConnect.filter((r) => r.status === filter) : state.schoolConnect;

  if (!rows.length) {
    list.innerHTML = state.schoolConnect.length
      ? '<div class="empty">No registrations with this status.</div>'
      : '<div class="empty">No School Connect registrations yet. They arrive here from /school-connect-register.</div>';
    return;
  }

  list.innerHTML = rows
    .map((r) => {
      const interests = Array.isArray(r.interests) ? r.interests.slice(0, 4) : [];
      const emailState =
        r.enrollment_email_state && r.enrollment_email_state !== 'sent'
          ? ` · <span style="color:#b45309;">ID email: ${escapeHtml(r.enrollment_email_state)}</span>`
          : r.enrollment_email_state === 'sent'
            ? ' · <span style="color:#047857;">ID email sent</span>'
            : '';
      const syncState =
        r.future_assist_state === 'synced'
          ? ' · <span style="color:#047857;">Future Assist ✓</span>'
          : r.future_assist_state && r.future_assist_state !== 'pending'
            ? ` · <span style="color:#b45309;">Future Assist: ${escapeHtml(r.future_assist_state)}</span>`
            : ' · <span style="color:#b45309;">Future Assist: pending</span>';
      return `
        <div class="card app-card">
          <div class="meta" style="flex:1;">
            <div class="title">${escapeHtml(r.student_name)} ${scStatusBadge(r.status)}</div>
            <div class="sub">
              ${escapeHtml(r.ref || '—')} · ${escapeHtml(r.grade || 'class not given')} · ${escapeHtml(r.current_school || '—')}
            </div>
            <div class="sub">
              ${escapeHtml([r.school_city, r.school_country].filter(Boolean).join(', ') || '—')}
              · Student: ${escapeHtml(r.student_email || '—')}
            </div>
            <div class="sub" style="margin-top:6px;">
              Parent: ${escapeHtml(r.parent_name || '—')} · ${escapeHtml(r.parent_email || '—')} · ${escapeHtml(r.parent_phone || '—')}${emailState}${syncState}
            </div>
            ${interests.length ? `<div class="chip-row">${interests.map((i) => `<span class="chip">${escapeHtml(i)}</span>`).join('')}</div>` : ''}
            ${r.school_id ? `<div class="sub" style="margin-top:6px;color:#b45309;font-weight:600;">School ID: ${escapeHtml(r.school_id)}</div>` : ''}
          </div>
          <div class="sub" style="white-space:nowrap;color:var(--muted);font-size:0.82rem;">${formatDate(r.created_at)}</div>
          <div class="row-actions">
            <button class="btn btn-ghost btn-sm" data-sc-open="${r.id}" type="button">Review →</button>
          </div>
        </div>`;
    })
    .join('');

  $$('#sc-list [data-sc-open]').forEach((btn) =>
    btn.addEventListener('click', () => openRegistration(Number(btn.dataset.scOpen)))
  );
}

async function openRegistration(id) {
  const { registration } = await api(`/api/admin/school-connect/${id}`);
  state.selectedRegistrationId = id;

  const interests = Array.isArray(registration.interests) ? registration.interests : [];
  const block = (label, value) =>
    value
      ? `<div class="app-block"><div class="app-label">${escapeHtml(label)}</div><div class="app-value">${escapeHtml(value)}</div></div>`
      : '';
  const mailto = (label, address) =>
    address
      ? `<div class="app-block"><div class="app-label">${escapeHtml(label)}</div><div class="app-value"><a href="mailto:${escapeHtml(address)}">${escapeHtml(address)}</a></div></div>`
      : '';

  $('#sc-modal-title').innerHTML = `${escapeHtml(registration.student_name)} <span class="pill">${escapeHtml(
    registration.ref || ''
  )}</span>`;

  $('#sc-modal-body').innerHTML = `
    <div class="app-grid">
      ${block('Registered', formatDate(registration.created_at))}
      ${block('Status', SC_STATUS_LABELS[registration.status] || registration.status)}
      ${block('Class', registration.grade)}
      ${block('Date of birth / age', [registration.date_of_birth ? String(registration.date_of_birth).slice(0, 10) : null, registration.age].filter(Boolean).join(' · '))}
      ${block('Nationality', registration.nationality)}
      ${block('Lives in', [registration.city, registration.country].filter(Boolean).join(', '))}
      ${mailto('Student email', registration.student_email)}
      ${block('Student phone / WhatsApp', registration.student_phone)}
      ${block('ID', [registration.id_type, registration.id_number].filter(Boolean).join(' · '))}
      ${block('ID issued in', registration.id_country)}
    </div>

    <h4 class="app-section">Present school</h4>
    <div class="app-grid">
      ${block('School', registration.current_school)}
      ${block('School city / country', [registration.school_city, registration.school_country].filter(Boolean).join(', '))}
      ${block('Curriculum', registration.curriculum)}
      ${block('Preferred language', registration.preferred_language)}
    </div>

    <h4 class="app-section">Parents / guardians</h4>
    <div class="app-grid">
      ${block('Parent 1', [registration.parent_name, registration.parent_relation].filter(Boolean).join(' · '))}
      ${mailto('Parent 1 email', registration.parent_email)}
      ${block('Parent 1 phone', registration.parent_phone)}
      ${block('Parent 1 occupation', registration.parent_occupation)}
      ${registration.parent2_name ? block('Parent 2', [registration.parent2_name, registration.parent2_relation].filter(Boolean).join(' · ')) : ''}
      ${registration.parent2_email ? mailto('Parent 2 email', registration.parent2_email) : ''}
      ${registration.parent2_phone ? block('Parent 2 phone', registration.parent2_phone) : ''}
    </div>

    <h4 class="app-section">Background</h4>
    ${interests.length ? `<div class="chip-row">${interests.map((i) => `<span class="chip">${escapeHtml(i)}</span>`).join('')}</div>` : ''}
    ${block('What the student is into', registration.about)}
    ${block('Profession / field aimed for', registration.goal)}
    ${block('Prior experience', registration.prior_experience)}
    ${block('Batch preference', registration.batch_preference)}
    ${block('Heard about us via', registration.heard_about)}

    <h4 class="app-section">Approval mail</h4>
    <div class="app-grid">
      ${block('School ID', registration.school_id)}
      ${block('Approved at', registration.approved_at ? formatDate(registration.approved_at) : '')}
      ${block('ID email', registration.enrollment_email_state)}
      ${block('ID email sent at', registration.enrollment_email_at ? formatDate(registration.enrollment_email_at) : '')}
      ${block('Reviewed by', registration.reviewed_by)}
      ${block('Future Assist row', registration.future_assist_id)}
      ${block(
        'Future Assist sync',
        registration.future_assist_state === 'synced'
          ? `Synced${
              registration.future_assist_synced_at ? ` · ${formatDate(registration.future_assist_synced_at)}` : ''
            }`
          : `${registration.future_assist_state || 'pending'}${
              registration.future_assist_error ? ` · ${registration.future_assist_error}` : ''
            }`
      )}
    </div>
    ${block('Consent recorded', registration.consent_registration ? 'Registration consent given' : 'Registration consent missing')}`;

  $('#sc-status').value = registration.status || 'new';
  $('#sc-school-id').value = registration.school_id || '';
  $('#sc-enrollment-note').value = registration.enrollment_note || '';
  $('#sc-notes').value = registration.reviewer_notes || '';

  $('#sc-modal').classList.remove('hidden');
}

function closeRegistrationModal() {
  $('#sc-modal').classList.add('hidden');
  state.selectedRegistrationId = null;
}

$('#sc-modal-close').addEventListener('click', closeRegistrationModal);
$('#sc-modal-close-2').addEventListener('click', closeRegistrationModal);
$('#sc-modal').addEventListener('click', (e) => {
  if (e.target === $('#sc-modal')) closeRegistrationModal();
});

async function patchRegistration(body, { confirmText, successText, button } = {}) {
  const id = state.selectedRegistrationId;
  if (!id) return;
  if (confirmText && !window.confirm(confirmText)) return;

  const old = button ? button.textContent : '';
  if (button) {
    button.disabled = true;
    button.textContent = 'Working…';
  }

  try {
    const { registration } = await api(`/api/admin/school-connect/${id}`, { method: 'PATCH', body });
    flash(
      registration.enrollment_email_state === 'failed'
        ? 'Saved, but the email could not be sent — check MAILGUN_API_KEY, then use Resend.'
        : successText || 'Registration updated'
    );
    await loadSchoolConnect();
    if (registration.enrollment_email_state === 'failed') {
      await openRegistration(id);
    } else {
      closeRegistrationModal();
    }
  } catch (err) {
    flash(err.message, 'error');
  } finally {
    if (button) {
      button.disabled = false;
      button.textContent = old;
    }
  }
}

$('#sc-save-btn').addEventListener('click', () => {
  patchRegistration(
    {
      status: $('#sc-status').value,
      reviewer_notes: $('#sc-notes').value,
      enrollment_note: $('#sc-enrollment-note').value,
      send_email: false,
    },
    { successText: 'Registration saved', button: $('#sc-save-btn') }
  );
});

$('#sc-approve-btn').addEventListener('click', () => {
  patchRegistration(
    {
      action: 'approve',
      reviewer_notes: $('#sc-notes').value,
      enrollment_note: $('#sc-enrollment-note').value,
    },
    {
      confirmText:
        'Approve this registration and email the Hash Future School ID to the student and parents?',
      successText: 'Approved — the ID email has been sent',
      button: $('#sc-approve-btn'),
    }
  );
});

$('#sc-resend-btn').addEventListener('click', () => {
  patchRegistration(
    {
      action: 'resend',
      enrollment_note: $('#sc-enrollment-note').value,
      reviewer_notes: $('#sc-notes').value,
    },
    { confirmText: 'Resend the ID email to the student and parents?', successText: 'ID email resent', button: $('#sc-resend-btn') }
  );
});

// The programme desk lives in Future Assist, so a registration whose first
// mirror failed (or a Future Assist that was down at the time) can be pushed
// again without touching the review status.
$('#sc-sync-btn').addEventListener('click', () => {
  patchRegistration(
    {
      action: 'sync',
      reviewer_notes: $('#sc-notes').value,
      enrollment_note: $('#sc-enrollment-note').value,
      send_email: false,
    },
    { successText: 'Pushed to Future Assist', button: $('#sc-sync-btn') }
  );
});

$('#sc-filter').addEventListener('change', renderSchoolConnect);
$('#sc-refresh-btn').addEventListener('click', async () => {
  await loadSchoolConnect();
  flash('Registrations refreshed');
});

// ---------- Site Content ----------
async function loadContent() {
  const { items } = await api('/api/admin/content');
  state.content = items;
  renderContent();
}

function renderContent() {
  const list = $('#content-list');
  if (!state.content.length) {
    list.innerHTML = '<div class="empty">No editable content yet.</div>';
    return;
  }
  list.innerHTML = state.content
    .map(
      (c) => `
        <div class="content-item card" style="flex-direction:column;align-items:stretch;">
          <div style="font-weight:700;font-size:0.9rem;color:var(--muted);">${escapeHtml(c.key)}</div>
          <textarea data-key="${escapeHtml(c.key)}" style="min-height:70px;">${escapeHtml(c.value)}</textarea>
        </div>`
    )
    .join('');
}

$('#save-content-btn').addEventListener('click', async () => {
  const entries = $$('#content-list textarea').map((ta) => ({
    key: ta.dataset.key,
    value: ta.value,
  }));
  try {
    await api('/api/admin/content', { method: 'PUT', body: { entries } });
    flash('Site content saved');
  } catch (err) {
    flash(err.message, 'error');
  }
});

bootstrap();
